fixing cache on github4

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -13,11 +13,11 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      - name: Set up JDK 23
+      - name: Set up JDK 24
         uses: actions/setup-java@v4
         with:
           distribution: 'temurin'
-          java-version: '23'
+          java-version: '24'
       - name: Cache Maven packages
         uses: actions/cache@v3
         with:
@@ -29,6 +29,9 @@ jobs:
 
       - name: Build with Maven
         run: mvn -B clean package --file pom.xml
+
+      - name: List build artifacts
+        run: ls -R target || echo "Target folder not found"
 
   docker:
     needs: build-and-test
